# Header
menu:
  Home: /
  Outdoors: /categories/Outdoors
  Food: /categories/Food
  Computers: /categories/Computers
  Archive: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- about
- tag
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

about: 'This is the blog of Nick Edwards. I live on New Zealand''s South Island
and am into various kinds of adventures in the outdoors, computers and
eating, cooking and growing food. For money, I develop control-system
software for <a href="https://www.hamiltonjet.com/">Hamilton Jet</a>. I help maintain
the website & IT systems for the <a href="https://ctc.org.nz">Christchurch Tramping Club</a>,
and a long time ago I was a member of <a href="http://atlas.ch/">The ATLAS Collaboration.</a>'
